import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const story = [
  ['THE STORY', 'It started with a phone call.', 'Three years ago, while still an undergraduate, something happened that has stayed with me till today.\n\nI have a cousin who is a seasonal farmer. Like many farmers, he only plants during the rainy season.\n\nThat year, there was a long break in rainfall - almost three months. Crops were already in the ground. Farmers around him started panicking.'],
  ['THE DISCOVERY', 'The forecast existed.', "The problem wasn't that there was no forecast.\n\nAs someone passionate about food security, I couldn't just watch. So I looked deeper.\n\nThat was when I discovered that NiMet had actually forecasted the prolonged dry spell.\n\nThe information existed - but it never reached the farm."],
  ['THE REAL PROBLEM', 'Information never got to the farmers who needed it most.', 'Early enough for them to plan. Early enough to save their crops.\n\nThat moment changed the way I saw the role of technology in agriculture.'],
  ['THE QUESTION', 'How can we bridge this communication gap?', "Since then, I've always asked myself that question.\n\nOver the years, I explored ways to access NiMet's weather data. I searched for their API, read documentation, even sent emails.\n\nI never got a response. For a while, I lost motivation."],
  ['TWO MONTHS AGO', 'Keep waiting... or start building?', 'A friend attended a Climate-Smart Agriculture event by NiMet in Ekiti State. I asked her to speak to organizers about API access for a sustainable agri solution.\n\nThe response was almost exactly what was on their website. They acknowledged the idea and mentioned they were also working on an app.\n\nAt that point, I realized I had two options.'],
  ['THE TURNING POINT', 'I swung into action.', 'At some point I even tried writing a research:\nDeterminants of Climate-Smart Agriculture and its impact on food security among smallholder farmers in Kwara State.\n\nBut something in me chose to do something stronger.'],
  ['BUILDING WITH OPEN DATA', 'Instead of waiting forever, I started building.', 'Bringing together trusted open climate and agricultural datasets from organizations around the world:\n\nOpen-Meteo Â· NASA POWER Â· CHIRPS Â· SoilGrids Â· OpenStreetMap Â· FAOSTAT Â· WorldClim Â· Copernicus Sentinel'],
  ['THE GOAL', 'One place for everything a farmer needs to decide.', 'To build a Climate Smart Agriculture app that gives farmers and stakeholders easier access to decision-support tools - all in one place.\n\nWeather forecasts Â· Rainfall history Â· Climate trends Â· Soil information Â· Crop recommendations Â· Seasonal insights Â· Interactive maps Â· Decision-support tools'],
  ['THIS IS JUST THE BEGINNING', 'Making climate information accessible and actionable.', "This project isn't about replacing NiMet or any institution.\n\nIt's about contributing, in my own little way, to making climate information more accessible for the people who need it most.\n\nIf we truly want to improve food security, getting the right information to farmers at the right time is just as important as producing it."]
];

export default function AppWeb() {
  const [page, setPage] = useState<'story' | 'onboarding'>('story');
  const [index, setIndex] = useState(0);
  if (page === 'onboarding') return <WebOnboarding onBack={() => setPage('story')} />;
  const card = story[index];
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.page}><View style={styles.nav}><Text style={styles.brand}>AgroCast</Text><Pressable style={styles.download} onPress={() => setPage('onboarding')}><Text style={styles.downloadText}>Download the app</Text></Pressable></View><View style={styles.hero}><Text style={styles.eyebrow}>CLIMATE-SMART AGRICULTURE</Text><Text style={styles.heroTitle}>Make the next farm decision with confidence.</Text><Text style={styles.heroBody}>Weather, rainfall, soil context, crop guidance, records, and farm economics in one practical toolkit.</Text><Pressable style={styles.primary} onPress={() => setPage('onboarding')}><Text style={styles.primaryText}>Open AgroCast web</Text></Pressable></View><View style={styles.story}><Text style={styles.eyebrow}>THE AGROCAST STORY</Text><Text style={styles.sectionTitle}>Why this work matters</Text><View style={styles.card}><View style={styles.art}><View style={styles.sun} /><View style={styles.fieldBack} /><View style={styles.fieldFront} /></View><Text style={styles.number}>{String(index + 1).padStart(2, '0')}</Text><Text style={styles.kicker}>{card[0]}</Text><Text style={styles.title}>{card[1]}</Text><Text style={styles.body}>{card[2]}</Text></View><View style={styles.controls}><Pressable onPress={() => setIndex((index - 1 + story.length) % story.length)}><Text style={styles.arrow}>â†</Text></Pressable><Text style={styles.counter}>{index + 1} / {story.length}</Text><Pressable onPress={() => setIndex((index + 1) % story.length)}><Text style={styles.arrow}>â†’</Text></Pressable></View></View></ScrollView></SafeAreaView>;
}

function WebOnboarding({ onBack }: { onBack: () => void }) { return <SafeAreaView style={styles.safe}><View style={styles.onboarding}><Text style={styles.brand}>AgroCast</Text><Text style={styles.sectionTitle}>Set up your web farm workspace</Text><Text style={styles.heroBody}>Choose your farm location and start using AgroCast tools in your browser. iOS downloads currently open this web onboarding because the native iOS bundle is not available yet.</Text><Pressable style={styles.primary} onPress={onBack}><Text style={styles.primaryText}>Back to story</Text></Pressable></View></SafeAreaView>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#FFFBF0' }, page: { paddingBottom: 80 }, nav: { height: 72, paddingHorizontal: 28, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#FFF' }, brand: { color: '#2D5A27', fontSize: 20, fontWeight: '900' }, download: { backgroundColor: '#2D5A27', borderRadius: 22, paddingHorizontal: 16, paddingVertical: 10 }, downloadText: { color: '#FFF', fontWeight: '800' }, hero: { maxWidth: 1100, width: '100%', alignSelf: 'center', padding: 70 }, eyebrow: { color: '#4A7C2E', fontSize: 11, fontWeight: '900', letterSpacing: 2 }, heroTitle: { maxWidth: 700, color: '#2D5A27', fontSize: 58, lineHeight: 61, fontWeight: '900', marginTop: 12 }, heroBody: { maxWidth: 650, color: '#5A5A5A', fontSize: 17, lineHeight: 27, marginTop: 16 }, primary: { alignSelf: 'flex-start', backgroundColor: '#2D5A27', borderRadius: 24, paddingHorizontal: 20, paddingVertical: 13, marginTop: 25 }, primaryText: { color: '#FFF', fontWeight: '900' }, story: { backgroundColor: '#FFFBF0', padding: 40, maxWidth: 1100, width: '100%', alignSelf: 'center' }, sectionTitle: { color: '#2D5A27', fontSize: 42, fontWeight: '900', marginTop: 8, marginBottom: 24 }, card: { backgroundColor: '#FFFDF7', borderRadius: 22, padding: 30, maxWidth: 700, minHeight: 480, borderWidth: 1, borderColor: '#D9DED6' }, art: { height: 100, overflow: 'hidden', borderRadius: 16, backgroundColor: '#F4F1E8', marginBottom: 22 }, sun: { position: 'absolute', width: 62, height: 62, borderRadius: 31, backgroundColor: '#E7C65A', top: 18, right: 42 }, fieldBack: { position: 'absolute', width: '120%', height: 90, bottom: -44, left: -30, borderRadius: 100, backgroundColor: '#8FB866', transform: [{ rotate: '-5deg' }] }, fieldFront: { position: 'absolute', width: '120%', height: 75, bottom: -42, right: -30, borderRadius: 100, backgroundColor: '#4F7D43', transform: [{ rotate: '5deg' }] }, number: { color: '#FFF', backgroundColor: '#2D5A27', alignSelf: 'flex-start', borderRadius: 14, paddingHorizontal: 11, paddingVertical: 8, fontWeight: '900' }, kicker: { color: '#4A7C2E', fontSize: 11, fontWeight: '900', letterSpacing: 1.5, marginTop: 20 }, title: { color: '#2D5A27', fontSize: 32, lineHeight: 36, fontWeight: '900', marginTop: 9 }, body: { color: '#2E2E2E', fontSize: 15, lineHeight: 24, marginTop: 16 }, controls: { maxWidth: 700, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 18 }, arrow: { color: '#2D5A27', fontSize: 28, padding: 8 }, counter: { color: '#65736B', fontWeight: '800' }, onboarding: { maxWidth: 700, width: '100%', alignSelf: 'center', padding: 50, marginTop: 80 } });

