import { MaterialCommunityIcons } from '@expo/vector-icons';
import { StyleSheet, Text, View } from 'react-native';
import { Card } from './components';
import { colors } from './theme';
import { SoilData, WeatherData, WeatherDay } from './types';

type Severity = 'high' | 'medium' | 'low';
type Hazard = { id: string; day: WeatherDay; title: string; detail: string; action: string; severity: Severity; icon: keyof typeof MaterialCommunityIcons.glyphMap };

function dateLabel(date: string) { return new Date(`${date}T12:00:00`).toLocaleDateString([], { weekday: 'short', day: 'numeric', month: 'short' }); }

function hazardsForDay(day: WeatherDay, humidity: number, soil: SoilData | null): Hazard[] {
  const hazards: Hazard[] = [];
  if (day.precipitation >= 50) hazards.push({ id: 'rain', day, title: 'Very heavy rainfall', detail: `${day.precipitation.toFixed(0)} mm forecast with ${day.precipitationProbability.toFixed(0)}% probability. Flash flooding and waterlogging are possible.`, action: 'Clear drains, protect stored inputs, and delay fertilizer or pesticide application.', severity: 'high', icon: 'weather-pouring' });
  else if (day.precipitation >= 25) hazards.push({ id: 'rain', day, title: 'Heavy rainfall', detail: `${day.precipitation.toFixed(0)} mm forecast. Low areas may collect water.`, action: 'Inspect drainage and avoid field operations that compact wet soil.', severity: 'medium', icon: 'weather-rainy' });
  if (day.apparentTemperatureMax >= 40) hazards.push({ id: 'heat', day, title: 'Dangerous heat stress', detail: `Feels-like temperature may reach ${day.apparentTemperatureMax.toFixed(0)}°C.`, action: 'Avoid midday labor, provide drinking water, shade seedlings, and irrigate only after checking soil.', severity: 'high', icon: 'thermometer-alert' });
  else if (day.apparentTemperatureMax >= 35) hazards.push({ id: 'heat', day, title: 'High heat', detail: `Feels-like temperature may reach ${day.apparentTemperatureMax.toFixed(0)}°C.`, action: 'Schedule strenuous work early and watch young or flowering crops for stress.', severity: 'medium', icon: 'weather-sunny-alert' });
  if (day.windSpeedMax >= 40) hazards.push({ id: 'wind', day, title: 'Strong wind', detail: `Gust-prone conditions with forecast wind near ${day.windSpeedMax.toFixed(0)} km/h.`, action: 'Delay spraying, support young crops, and secure sheets, covers, and tools.', severity: day.windSpeedMax >= 55 ? 'high' : 'medium', icon: 'weather-windy' });
  if (day.uvIndexMax >= 8) hazards.push({ id: 'uv', day, title: 'Very high UV exposure', detail: `Maximum UV index is forecast near ${day.uvIndexMax.toFixed(0)}.`, action: 'Use a hat, long clothing, shade, and avoid prolonged midday exposure.', severity: day.uvIndexMax >= 11 ? 'high' : 'medium', icon: 'sun-wireless-outline' });
  if (humidity >= 85 && day.precipitation >= 3) hazards.push({ id: 'humidity', day, title: 'High humidity and disease pressure', detail: `Current humidity is ${humidity.toFixed(0)}% with wet weather forecast. Leaf wetness may remain high.`, action: 'Scout for fungal symptoms, improve airflow, and avoid unnecessary overhead watering.', severity: 'medium', icon: 'water-percent-alert' });
  if (day.precipitation >= 30 && (soil?.texture === 'Sandy' || soil?.texture === 'Silty')) hazards.push({ id: 'erosion', day, title: 'Soil erosion risk', detail: `${day.precipitation.toFixed(0)} mm of rain may move exposed ${soil.texture.toLowerCase()} topsoil, especially on slopes.`, action: 'Keep soil covered, open safe drainage paths, reinforce contour barriers, and avoid fresh tillage.', severity: day.precipitation >= 50 ? 'high' : 'medium', icon: 'landslide-outline' });
  return hazards;
}

export function EnvironmentalAlerts({ weather, soil }: { weather: WeatherData | null; soil: SoilData | null }) {
  if (!weather) return <Card style={styles.empty}><Text style={styles.emptyTitle}>No forecast available</Text><Text style={styles.emptyText}>Connect once to download the seven-day hazard outlook. It will then remain available offline.</Text></Card>;
  const hazards = weather.daily.flatMap((day) => hazardsForDay(day, weather.current.humidity, soil)).sort((a, b) => (a.day.date.localeCompare(b.day.date) || ({ high: 0, medium: 1, low: 2 }[a.severity] - { high: 0, medium: 1, low: 2 }[b.severity])));
  const totalRain = weather.daily.reduce((sum, day) => sum + day.precipitation, 0);
  const dryStress = totalRain < 5 && weather.daily.reduce((sum, day) => sum + day.evapotranspiration, 0) >= 20;
  if (dryStress) hazards.unshift({ id: 'dry', day: weather.daily[0]!, title: 'Seven-day dry-spell stress', detail: `Only ${totalRain.toFixed(1)} mm of rain is forecast while estimated atmospheric water demand is high.`, action: 'Conserve soil moisture, control weeds, mulch where practical, and prioritize irrigation for sensitive stages.', severity: 'medium', icon: 'water-alert-outline' });
  return <View><View style={styles.summary}><View><Text style={styles.summaryLabel}>7-DAY HAZARD OUTLOOK</Text><Text style={styles.summaryValue}>{hazards.length ? `${hazards.length} signal${hazards.length === 1 ? '' : 's'} detected` : 'No major hazards detected'}</Text></View><View style={[styles.status, { backgroundColor: hazards.some((h) => h.severity === 'high') ? '#FCE0DC' : hazards.length ? colors.warningBg : colors.primarySoft }]}><MaterialCommunityIcons name={hazards.length ? 'alert-outline' : 'check-circle-outline'} size={23} color={hazards.some((h) => h.severity === 'high') ? colors.error : hazards.length ? colors.warning : colors.primary} /></View></View>{hazards.length ? hazards.map((hazard, index) => <Card key={`${hazard.id}-${hazard.day.date}-${index}`} style={[styles.alert, hazard.severity === 'high' && styles.high]}><View style={styles.alertTop}><View style={[styles.icon, { backgroundColor: hazard.severity === 'high' ? '#FCE0DC' : colors.warningBg }]}><MaterialCommunityIcons name={hazard.icon} size={24} color={hazard.severity === 'high' ? colors.error : colors.warning} /></View><View style={styles.flex}><View style={styles.titleRow}><Text style={styles.title}>{hazard.title}</Text><Text style={styles.date}>{dateLabel(hazard.day.date)}</Text></View><Text style={styles.detail}>{hazard.detail}</Text></View></View><View style={styles.action}><MaterialCommunityIcons name="arrow-right-circle-outline" size={18} color={colors.primary} /><Text style={styles.actionText}>{hazard.action}</Text></View></Card>) : <Card style={styles.clear}><MaterialCommunityIcons name="shield-check-outline" size={35} color={colors.primary} /><Text style={styles.clearTitle}>Conditions look manageable</Text><Text style={styles.clearText}>Continue checking daily. Forecasts can change, particularly during the rainy season.</Text></Card>}<Text style={styles.note}>Erosion risk is an estimate based on forecast rainfall and SoilGrids topsoil texture. Field slope, ground cover, drainage, and actual rainfall can change the risk.</Text></View>;
}

const styles = StyleSheet.create({ summary: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 15 }, summaryLabel: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, summaryValue: { color: colors.text, fontSize: 18, fontWeight: '900', marginTop: 3 }, status: { width: 45, height: 45, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, alert: { marginBottom: 10 }, high: { borderColor: '#E7AAA2' }, alertTop: { flexDirection: 'row', gap: 11 }, icon: { width: 43, height: 43, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 6 }, title: { color: colors.text, fontWeight: '900', flex: 1 }, date: { color: colors.muted, fontSize: 10, fontWeight: '700' }, detail: { color: colors.muted, lineHeight: 19, fontSize: 12, marginTop: 4 }, action: { flexDirection: 'row', gap: 7, backgroundColor: colors.primarySoft, padding: 10, borderRadius: 11, marginTop: 12 }, actionText: { color: colors.primaryDark, fontSize: 12, lineHeight: 17, flex: 1, fontWeight: '600' }, note: { color: colors.muted, fontSize: 10, lineHeight: 15, fontStyle: 'italic', marginTop: 5 }, empty: { marginBottom: 12 }, emptyTitle: { color: colors.text, fontWeight: '900' }, emptyText: { color: colors.muted, lineHeight: 19, marginTop: 5 }, clear: { alignItems: 'center', marginBottom: 12 }, clearTitle: { color: colors.text, fontWeight: '900', fontSize: 17, marginTop: 8 }, clearText: { color: colors.muted, textAlign: 'center', lineHeight: 19, marginTop: 4 } });
