import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card } from './components';
import { farmGuides, GuideArticle } from './farmGuides';
import { colors } from './theme';

export function FarmingGuides() {
  const [query, setQuery] = useState(''); const [article, setArticle] = useState<GuideArticle | null>(null);
  const filtered = useMemo(() => farmGuides.filter((guide) => `${guide.title} ${guide.category} ${guide.summary}`.toLowerCase().includes(query.toLowerCase())), [query]);
  if (article) return <View><Pressable style={styles.back} onPress={() => setArticle(null)}><MaterialCommunityIcons name="arrow-left" size={20} color={colors.primary} /><Text style={styles.backText}>All guides</Text></Pressable><View style={styles.articleHead}><View style={styles.bigIcon}><MaterialCommunityIcons name={article.icon} size={31} color={colors.primary} /></View><View style={styles.flex}><Text style={styles.category}>{article.category.toUpperCase()}</Text><Text style={styles.articleTitle}>{article.title}</Text><Text style={styles.updated}>Reviewed {article.updated}</Text></View></View>{article.steps.map((step, index) => <Card key={step.title} style={styles.step}><View style={styles.number}><Text style={styles.numberText}>{index + 1}</Text></View><View style={styles.flex}><Text style={styles.stepTitle}>{step.title}</Text><Text style={styles.stepText}>{step.text}</Text></View></Card>)}<Text style={styles.caution}>Adapt these practices to your crop, field, local regulations, and extension advice.</Text></View>;
  return <View><View style={styles.search}><MaterialCommunityIcons name="magnify" size={21} color={colors.muted} /><TextInput value={query} onChangeText={setQuery} placeholder="Search guides" placeholderTextColor={colors.muted} style={styles.input} /></View><View style={styles.status}><MaterialCommunityIcons name="cloud-check-outline" size={18} color={colors.primary} /><Text style={styles.statusText}>{farmGuides.length} reviewed guides available offline</Text></View>{filtered.map((guide) => <Pressable key={guide.id} onPress={() => setArticle(guide)}><Card style={styles.guide}><View style={styles.icon}><MaterialCommunityIcons name={guide.icon} size={25} color={colors.primary} /></View><View style={styles.flex}><Text style={styles.category}>{guide.category.toUpperCase()}</Text><Text style={styles.guideTitle}>{guide.title}</Text><Text style={styles.summary}>{guide.summary}</Text></View><MaterialCommunityIcons name="chevron-right" size={22} color={colors.muted} /></Card></Pressable>)}{!filtered.length ? <Card><Text style={styles.guideTitle}>No matching guide</Text><Text style={styles.summary}>Try a crop activity such as irrigation, storage, soil, planting, or pests.</Text></Card> : null}</View>;
}
const styles = StyleSheet.create({ search: { height: 51, borderWidth: 1, borderColor: colors.border, backgroundColor: '#FFF', borderRadius: 14, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, gap: 8 }, input: { flex: 1, color: colors.text, fontSize: 15 }, status: { flexDirection: 'row', alignItems: 'center', gap: 7, marginVertical: 13 }, statusText: { color: colors.primary, fontWeight: '700', fontSize: 11 }, guide: { flexDirection: 'row', alignItems: 'center', gap: 11, marginBottom: 9, padding: 14 }, icon: { width: 45, height: 45, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, flex: { flex: 1 }, category: { color: colors.primary, fontSize: 9, fontWeight: '900', letterSpacing: 1 }, guideTitle: { color: colors.text, fontWeight: '900', fontSize: 15, marginTop: 3 }, summary: { color: colors.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, back: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 16 }, backText: { color: colors.primary, fontWeight: '800' }, articleHead: { flexDirection: 'row', gap: 12, marginBottom: 18 }, bigIcon: { width: 58, height: 58, borderRadius: 17, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, articleTitle: { color: colors.text, fontSize: 21, fontWeight: '900', marginTop: 3 }, updated: { color: colors.muted, fontSize: 10, marginTop: 4 }, step: { flexDirection: 'row', gap: 10, marginBottom: 9 }, number: { width: 27, height: 27, borderRadius: 14, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, numberText: { color: '#FFF', fontWeight: '900', fontSize: 11 }, stepTitle: { color: colors.text, fontWeight: '900' }, stepText: { color: colors.muted, fontSize: 12, lineHeight: 19, marginTop: 4 }, caution: { color: colors.muted, fontSize: 10, fontStyle: 'italic', lineHeight: 15 } });
