import { MaterialCommunityIcons } from '@expo/vector-icons';
import { useMemo, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { crops } from './agronomy';
import { farmGuides } from './farmGuides';
import { pestKnowledge, pestRisk } from './pestKnowledge';
import { colors } from './theme';
import { FarmLocation, RainfallData, SoilData, WeatherData } from './types';

type Message = { id: number; role: 'user' | 'assistant'; text: string };
type Context = { location: FarmLocation | null; weather: WeatherData | null; soil: SoilData | null; rainfall: RainfallData | null; cached: boolean };

function answerQuestion(question: string, context: Context) {
  const q = question.toLowerCase(); const crop = crops.find((item) => q.includes(item.name.toLowerCase()));
  if (/weather|rain|forecast|heat|wind|humidity/.test(q) && context.weather) { const rain = context.weather.daily.slice(0, 7).reduce((sum, day) => sum + day.precipitation, 0); const hottest = Math.max(...context.weather.daily.map((day) => day.temperatureMax)); return `For ${context.location?.name ?? 'your farm'}, the saved 7-day forecast shows about ${rain.toFixed(1)} mm of rain and a maximum temperature near ${hottest.toFixed(0)}°C. Current humidity is ${context.weather.current.humidity.toFixed(0)}%. ${context.cached ? 'This is cached data, so check the last-updated time before acting.' : 'This is the latest downloaded forecast.'}`; }
  if (/soil|ph|texture/.test(q) && context.soil) return `The SoilGrids estimate for your farm is ${context.soil.texture.toLowerCase()} topsoil with about ${context.soil.sand?.toFixed(0) ?? 'unknown'}% sand, ${context.soil.clay?.toFixed(0) ?? 'unknown'}% clay, and pH ${context.soil.ph?.toFixed(1) ?? 'unknown'}. Treat this as context; use a field soil test for fertilizer rates.`;
  if (/pest|disease|symptom|leaf|worm|blight|aphid/.test(q)) { const matches = pestKnowledge.filter((entry) => !crop || entry.crops.includes(crop.id)).map((entry) => ({ entry, risk: pestRisk(entry, context.weather) })).sort((a, b) => ({ high: 0, moderate: 1, low: 2 }[a.risk.level] - { high: 0, moderate: 1, low: 2 }[b.risk.level])).slice(0, 3); return matches.length ? `${crop ? `For ${crop.name},` : 'Based on the crops in the guide,'} inspect for ${matches.map(({ entry, risk }) => `${entry.name} (${risk.level} weather risk)`).join(', ')}. Open Crops > Pest & disease risk to compare symptoms before treating.` : 'Tell me which crop is affected and what you see on the leaves, stems, roots, fruit, or growing point.'; }
  if (crop && /plant|calendar|season|when/.test(q)) return `${crop.name}: ${crop.plantingTip} Typical maturity is about ${crop.maturityDays} days, depending on variety and conditions. Open Crops > Planting calendar for the month-by-month window for your farm zone.`;
  if (crop && /fertili|nutrient|npk|urea/.test(q)) return `${crop.name}: ${crop.fertilizerTip} Place fertilizer away from seed, roots, and stems, apply to moist non-waterlogged soil, and use a local soil test for exact product and rate.`;
  if (crop && /water|irrigat|dry/.test(q)) return `${crop.name} uses about ${crop.rainNeed} mm as AgroCast's short-term water benchmark. Check moisture below the surface and use the crop-specific irrigation playbook under Crops > Irrigation advice.`;
  if (/profit|cost|money|price|revenue/.test(q)) return 'Use Tools > Cost & profit to enter farm size, expected yield, price, and total cost. Include family labor, transport, storage losses, rent, and finance costs so the estimate is realistic.';
  const guide = farmGuides.find((item) => `${item.title} ${item.summary} ${item.steps.map((step) => `${step.title} ${step.text}`).join(' ')}`.toLowerCase().split(' ').filter((word) => word.length > 4).some((word) => q.includes(word)));
  if (guide) return `${guide.title}: ${guide.steps.slice(0, 3).map((step) => `${step.title} - ${step.text}`).join(' ')} Open Farming guides for the complete checklist.`;
  return 'I can answer from AgroCast’s offline guides and saved farm data. Include the crop and task, for example: “Should I irrigate maize?”, “What disease affects tomato leaves?”, “When should I plant yam?”, or “What is my soil pH?”';
}

export function FarmAssistant({ context }: { context: Context }) {
  const [input, setInput] = useState(''); const [messages, setMessages] = useState<Message[]>([{ id: 1, role: 'assistant', text: 'Ask about your forecast, soil, crops, planting, irrigation, fertilizer, pests, storage, or farm costs. I answer locally from AgroCast data.' }]); const scroll = useRef<ScrollView>(null);
  const suggestions = useMemo(() => ['Will it rain this week?', 'What is my soil type?', 'When should I plant maize?', 'Pest risk for tomato'], []);
  function send(value = input) { const text = value.trim(); if (!text) return; const nextId = Date.now(); setMessages((current) => [...current, { id: nextId, role: 'user', text }, { id: nextId + 1, role: 'assistant', text: answerQuestion(text, context) }]); setInput(''); setTimeout(() => scroll.current?.scrollToEnd({ animated: true }), 50); }
  return <KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={styles.dataBar}><MaterialCommunityIcons name={context.cached ? 'cloud-off-outline' : 'database-check-outline'} size={18} color={context.cached ? colors.warning : colors.primary} /><Text style={[styles.dataText, context.cached && { color: colors.warning }]}>{context.weather ? `${context.cached ? 'Cached' : 'Latest'} farm data connected` : 'Offline guides connected; no weather downloaded'}</Text></View><ScrollView ref={scroll} style={styles.chat} contentContainerStyle={styles.chatContent} nestedScrollEnabled>{messages.map((message) => <View key={message.id} style={[styles.message, message.role === 'user' ? styles.userMessage : styles.botMessage]}>{message.role === 'assistant' ? <MaterialCommunityIcons name="leaf" size={17} color={colors.primary} style={styles.botIcon} /> : null}<Text style={[styles.messageText, message.role === 'user' && styles.userText]}>{message.text}</Text></View>)}</ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.suggestions}>{suggestions.map((suggestion) => <Pressable key={suggestion} style={styles.suggestion} onPress={() => send(suggestion)}><Text style={styles.suggestionText}>{suggestion}</Text></Pressable>)}</ScrollView><View style={styles.composer}><TextInput value={input} onChangeText={setInput} onSubmitEditing={() => send()} placeholder="Ask a farming question" placeholderTextColor={colors.muted} style={styles.input} multiline maxLength={400} /><Pressable onPress={() => send()} style={[styles.send, !input.trim() && styles.sendDisabled]} disabled={!input.trim()}><MaterialCommunityIcons name="send" size={20} color="#FFF" /></Pressable></View><Text style={styles.privacy}>Private offline chat. Messages are not uploaded or stored after this screen closes.</Text></KeyboardAvoidingView>;
}
const styles = StyleSheet.create({ dataBar: { flexDirection: 'row', gap: 7, alignItems: 'center', backgroundColor: colors.primarySoft, borderRadius: 11, padding: 10, marginBottom: 10 }, dataText: { color: colors.primary, fontSize: 11, fontWeight: '800' }, chat: { height: 390, backgroundColor: '#EFF1EC', borderRadius: 16 }, chatContent: { padding: 12, gap: 10 }, message: { maxWidth: '88%', borderRadius: 15, padding: 11, flexDirection: 'row', gap: 7 }, botMessage: { alignSelf: 'flex-start', backgroundColor: '#FFF', borderBottomLeftRadius: 4 }, userMessage: { alignSelf: 'flex-end', backgroundColor: colors.primary, borderBottomRightRadius: 4 }, botIcon: { marginTop: 1 }, messageText: { color: colors.text, lineHeight: 19, fontSize: 13, flexShrink: 1 }, userText: { color: '#FFF' }, suggestions: { gap: 7, paddingVertical: 10 }, suggestion: { borderWidth: 1, borderColor: colors.border, backgroundColor: '#FFF', borderRadius: 16, paddingHorizontal: 11, paddingVertical: 8 }, suggestionText: { color: colors.primary, fontSize: 11, fontWeight: '700' }, composer: { minHeight: 54, flexDirection: 'row', alignItems: 'flex-end', gap: 8, borderWidth: 1, borderColor: colors.border, backgroundColor: '#FFF', borderRadius: 15, padding: 6 }, input: { flex: 1, color: colors.text, paddingHorizontal: 8, paddingVertical: 8, maxHeight: 100 }, send: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, sendDisabled: { opacity: 0.4 }, privacy: { color: colors.muted, fontSize: 9, textAlign: 'center', marginTop: 7 } });
