import { WeatherData } from './types';

export type PestRisk = 'low' | 'moderate' | 'high';
export type PestEntry = {
  id: string; name: string; crops: string[]; kind: 'Pest' | 'Disease';
  warmWet?: boolean; hotDry?: boolean; heavyRain?: boolean;
  symptoms: string[]; inspect: string[]; prevention: string[]; management: string[];
};

export const pestKnowledge: PestEntry[] = [
  { id: 'armyworm', name: 'Fall armyworm', crops: ['maize', 'sorghum', 'millet'], kind: 'Pest', warmWet: true, symptoms: ['Ragged holes and window-like feeding on young leaves', 'Fresh frass deep inside the leaf whorl', 'Young plants may lose the growing point'], inspect: ['Open the whorl and look for larvae and fresh frass', 'Check field edges and late-planted sections first'], prevention: ['Plant within the recommended local window', 'Remove volunteer maize and manage grass weeds', 'Scout at least twice weekly during early growth'], management: ['Hand-pick larvae in small plots where practical', 'Use locally approved biological controls where available', 'Only use a registered pesticide after confirming the pest and threshold; direct application into the whorl and follow the label'], },
  { id: 'maize_streak', name: 'Maize streak virus', crops: ['maize'], kind: 'Disease', hotDry: true, symptoms: ['Narrow pale or yellow streaks running along leaves', 'Stunted plants and poorly formed cobs', 'Symptoms are most severe when infection occurs early'], inspect: ['Compare several plants across the field', 'Look for leafhopper activity and nearby grass hosts'], prevention: ['Use resistant or tolerant varieties', 'Plant promptly and remove volunteer maize', 'Control grassy weeds around the field'], management: ['Remove severely infected young plants where incidence is low', 'Do not use seed from badly affected fields', 'Seek extension advice when symptoms spread quickly'], },
  { id: 'cassava_mosaic', name: 'Cassava mosaic disease', crops: ['cassava'], kind: 'Disease', symptoms: ['Patchy light and dark green mosaic pattern', 'Distorted, narrow leaves', 'Stunting and reduced root development'], inspect: ['Check the youngest fully opened leaves', 'Compare symptoms across plants from the same cutting source'], prevention: ['Plant certified or visibly healthy stems', 'Use resistant varieties', 'Do not move cuttings from affected fields'], management: ['Uproot severely affected plants early and destroy them safely', 'Replace with healthy planting material', 'Manage whitefly pressure using approved integrated methods'], },
  { id: 'cassava_blight', name: 'Cassava bacterial blight', crops: ['cassava'], kind: 'Disease', warmWet: true, heavyRain: true, symptoms: ['Angular water-soaked leaf spots', 'Leaf blight, wilting, and dieback', 'Sticky gum may appear on stems or petioles'], inspect: ['Look for angular lesions bordered by leaf veins', 'Inspect stems for dieback and gum exudate'], prevention: ['Use clean, disease-free cuttings', 'Disinfect cutting tools between fields', 'Avoid working through wet plants'], management: ['Remove heavily infected plants and residues', 'Avoid moving stems from the field', 'Rotate away from cassava and seek extension confirmation'], },
  { id: 'yam_anthracnose', name: 'Yam anthracnose', crops: ['yam'], kind: 'Disease', warmWet: true, heavyRain: true, symptoms: ['Dark leaf spots that expand and merge', 'Blackened stems and shoot dieback', 'Premature leaf drop'], inspect: ['Inspect lower and inner canopy leaves after wet weather', 'Check vines for dark lesions'], prevention: ['Use tolerant varieties and healthy seed yam', 'Provide good staking and airflow', 'Remove infected crop debris'], management: ['Remove badly infected leaves when practical', 'Avoid overhead irrigation late in the day', 'Use only locally registered fungicides with extension guidance'], },
  { id: 'cowpea_aphid', name: 'Cowpea aphid', crops: ['cowpea', 'groundnut', 'soybean'], kind: 'Pest', hotDry: true, symptoms: ['Clusters of dark aphids on shoots and leaf undersides', 'Curling leaves and sticky honeydew', 'Stunting and flower or pod loss'], inspect: ['Check tender shoots and leaf undersides', 'Look for ants and sticky surfaces'], prevention: ['Plant on time and control volunteer host plants', 'Encourage beneficial insects by avoiding unnecessary sprays', 'Maintain balanced crop nutrition'], management: ['Crush small colonies or use a strong water spray where practical', 'Use soap or approved botanical products according to local guidance', 'Apply registered insecticide only when infestation is damaging and beneficial insects are insufficient'], },
  { id: 'rice_blast', name: 'Rice blast', crops: ['rice'], kind: 'Disease', warmWet: true, symptoms: ['Diamond-shaped leaf lesions with grey centres', 'Dark lesions on nodes or panicle necks', 'Empty or poorly filled grains after neck infection'], inspect: ['Check dense, shaded parts of the field', 'Inspect leaves after humid nights and panicle necks near heading'], prevention: ['Use resistant varieties and clean seed', 'Avoid excessive nitrogen', 'Maintain appropriate spacing and water management'], management: ['Correct excessive nitrogen and improve airflow', 'Remove infected residues after harvest', 'Consult extension services before any fungicide application'], },
  { id: 'groundnut_rosette', name: 'Groundnut rosette disease', crops: ['groundnut'], kind: 'Disease', hotDry: true, symptoms: ['Severe stunting and shortened internodes', 'Yellow or green mottled leaves', 'Bushy plants with little or no pod production'], inspect: ['Look for aphids on young shoots', 'Check whether affected plants occur in expanding patches'], prevention: ['Use resistant varieties and plant early at recommended density', 'Remove volunteer groundnut plants', 'Reduce aphid spread through integrated management'], management: ['Remove early infection sources when incidence is low', 'Do not save seed from affected plants', 'Seek local advice for severe outbreaks'], },
  { id: 'tomato_blight', name: 'Tomato early/late blight risk', crops: ['tomato', 'pepper'], kind: 'Disease', warmWet: true, heavyRain: true, symptoms: ['Brown leaf spots that expand during wet weather', 'Yellowing and rapid leaf death', 'Dark lesions may develop on stems or fruit'], inspect: ['Start with older and lower leaves', 'Check dense areas that remain wet longest'], prevention: ['Stake and space plants for airflow', 'Water at soil level rather than over leaves', 'Rotate away from tomato-family crops and remove infected residue'], management: ['Remove affected leaves using clean tools', 'Avoid handling wet plants', 'Use a registered fungicide only after proper diagnosis and follow pre-harvest intervals'], },
  { id: 'vegetable_whitefly', name: 'Whitefly and virus risk', crops: ['tomato', 'pepper', 'okra', 'cassava'], kind: 'Pest', hotDry: true, symptoms: ['Tiny white insects fly up when leaves are disturbed', 'Yellowing, curling, or sticky leaves', 'Virus symptoms such as mosaic, curling, and stunting'], inspect: ['Turn over young leaves and count adults or immature scales', 'Check weeds and nearby older crops'], prevention: ['Use healthy seedlings and remove weed hosts', 'Avoid overlapping old and new crops', 'Use reflective mulch or fine netting where practical'], management: ['Remove severely virus-affected plants', 'Preserve natural enemies and avoid repeated broad-spectrum spraying', 'Use registered products only when monitoring shows damaging populations'], },
  { id: 'okra_flea', name: 'Okra flea beetle and leaf feeders', crops: ['okra'], kind: 'Pest', hotDry: true, symptoms: ['Numerous small round holes in young leaves', 'Seedlings may be weakened or growth delayed', 'Small beetles jump when disturbed'], inspect: ['Check seedlings early in the morning', 'Inspect field borders first'], prevention: ['Keep the field and borders free of alternative hosts', 'Plant vigorous seed and avoid delayed establishment', 'Use protective netting on small beds where practical'], management: ['Hand-pick or use approved botanical controls in small plots', 'Treat only if young plants are losing substantial leaf area', 'Follow local pesticide labels and protect pollinators'], },
  { id: 'plantain_sigatoka', name: 'Black Sigatoka leaf spot', crops: ['plantain'], kind: 'Disease', warmWet: true, symptoms: ['Fine reddish-brown streaks that become dark leaf spots', 'Large dead areas and premature leaf drying', 'Smaller bunches and poor fruit filling'], inspect: ['Check the underside of younger leaves for early streaks', 'Monitor fields after extended humid or rainy periods'], prevention: ['Use clean planting material and adequate spacing', 'Remove heavily spotted dead leaves', 'Maintain drainage and balanced nutrition'], management: ['Prune severely affected leaf tissue without over-defoliating', 'Destroy infected residues appropriately', 'Coordinate any fungicide program with extension guidance to avoid resistance'], },
  { id: 'root_rot', name: 'Root and corm rot', crops: ['cassava', 'yam', 'cocoyam', 'plantain'], kind: 'Disease', heavyRain: true, symptoms: ['Yellowing and sudden wilting despite wet soil', 'Soft, discoloured, or foul-smelling roots or corms', 'Plants pull out easily or collapse at the base'], inspect: ['Check low-lying and poorly drained areas', 'Cut affected roots or corms to inspect internal discolouration'], prevention: ['Plant on ridges or mounds with reliable drainage', 'Use healthy planting material', 'Avoid moving contaminated soil or tools'], management: ['Improve drainage immediately', 'Remove badly rotted plants and contaminated material', 'Do not replant susceptible crops in the same wet spot without correction'], },
];

export function pestRisk(entry: PestEntry, weather: WeatherData | null): { level: PestRisk; reason: string } {
  if (!weather) return { level: 'moderate', reason: 'No current weather is available, so inspect the field directly.' };
  const days = weather.daily.slice(0, 7); const rain = days.reduce((sum, day) => sum + day.precipitation, 0);
  const hot = days.filter((day) => day.temperatureMax >= 33).length; const wet = days.filter((day) => day.precipitation >= 3).length;
  let points = 0; const reasons: string[] = [];
  if (entry.warmWet && weather.current.humidity >= 75 && wet >= 2) { points += 2; reasons.push('warm, humid and wet conditions'); }
  if (entry.hotDry && hot >= 3 && rain < 15) { points += 2; reasons.push('several hot days with limited rain'); }
  if (entry.heavyRain && rain >= 35) { points += 2; reasons.push(`${rain.toFixed(0)} mm forecast rainfall`); }
  if (!entry.warmWet && !entry.hotDry && !entry.heavyRain) { points = 1; reasons.push('weather is not the main driver'); }
  return { level: points >= 2 ? 'high' : points === 1 ? 'moderate' : 'low', reason: reasons.length ? reasons.join(' and ') : 'forecast conditions are currently less favourable' };
}
