import { useMemo, useState } from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { CropSelector } from './CropAnalysis';
import { crops } from './agronomy';
import { Card } from './components';
import { colors } from './theme';

type Scenario = { area: string; yieldKg: string; price: string; costPerHa: string; losses: string };
const yieldDefaults: Record<string, number> = { maize: 2500, cassava: 15000, yam: 10000, cowpea: 1200, rice: 3000, sorghum: 1800, millet: 1400, groundnut: 1500, soybean: 1800, tomato: 12000, pepper: 6000, okra: 5000, plantain: 12000, cocoyam: 8000 };
function initialScenario(cropId: string): Scenario { return { area: '1', yieldKg: String(yieldDefaults[cropId] ?? 2000), price: '', costPerHa: '', losses: '10' }; }

export function ProfitEstimator() {
  const [crop, setCrop] = useState(crops[0]!);
  const [scenarios, setScenarios] = useState<Record<string, Scenario>>(() => Object.fromEntries(crops.map((item) => [item.id, initialScenario(item.id)])));
  const scenario = scenarios[crop.id]!;
  function update(field: keyof Scenario, value: string) { setScenarios((current) => ({ ...current, [crop.id]: { ...current[crop.id]!, [field]: value } })); }
  const values = useMemo(() => { const area = Number(scenario.area) || 0; const yieldPerHa = Number(scenario.yieldKg) || 0; const price = Number(scenario.price) || 0; const costPerHa = Number(scenario.costPerHa) || 0; const lossRate = Math.min(100, Math.max(0, Number(scenario.losses) || 0)) / 100; const grossHarvest = area * yieldPerHa; const saleableHarvest = grossHarvest * (1 - lossRate); const revenue = saleableHarvest * price; const totalCost = area * costPerHa; return { grossHarvest, saleableHarvest, revenue, totalCost, profit: revenue - totalCost, margin: revenue > 0 ? (revenue - totalCost) / revenue * 100 : 0, breakEven: saleableHarvest > 0 ? totalCost / saleableHarvest : 0 }; }, [scenario]);
  return <View><Text style={styles.controlLabel}>SELECT CROP</Text><CropSelector value={crop} onChange={setCrop} /><Card style={styles.cropBanner}><Text style={styles.cropName}>{crop.name} enterprise</Text><Text style={styles.cropHint}>Each crop keeps its own calculation while you switch. Replace the starting yield with your expected farm yield.</Text></Card><View style={styles.grid}><Field label="FARM SIZE (HA)" value={scenario.area} onChange={(value) => update('area', value)} /><Field label="YIELD / HA (KG)" value={scenario.yieldKg} onChange={(value) => update('yieldKg', value)} /><Field label="SELLING PRICE / KG" value={scenario.price} onChange={(value) => update('price', value)} placeholder="Enter local price" /><Field label="COST / HA" value={scenario.costPerHa} onChange={(value) => update('costPerHa', value)} placeholder="All production costs" /><Field label="EXPECTED LOSS (%)" value={scenario.losses} onChange={(value) => update('losses', value)} /></View><Card style={styles.result}><Text style={styles.resultLabel}>ESTIMATED {crop.name.toUpperCase()} PROFIT</Text><Text style={[styles.profit, { color: values.profit >= 0 ? colors.primary : colors.error }]}>₦{Math.round(values.profit).toLocaleString()}</Text><Metric label="Gross harvest" value={`${Math.round(values.grossHarvest).toLocaleString()} kg`} /><Metric label="Saleable harvest" value={`${Math.round(values.saleableHarvest).toLocaleString()} kg`} /><Metric label="Revenue" value={`₦${Math.round(values.revenue).toLocaleString()}`} /><Metric label="Total cost" value={`₦${Math.round(values.totalCost).toLocaleString()}`} /><Metric label="Break-even price" value={`₦${Math.round(values.breakEven).toLocaleString()}/kg`} /><Metric label="Profit margin" value={`${values.margin.toFixed(1)}%`} /></Card><Card style={styles.checklist}><Text style={styles.checkTitle}>Costs to include for {crop.name}</Text><Text style={styles.checkText}>Seed or planting material · land preparation · fertilizer and manure · crop protection · hired and family labor · irrigation · harvesting · bags or crates · storage · transport · market fees · loan interest · expected losses</Text></Card><Text style={styles.note}>Planning estimates are not market prices or guarantees. Use your farm records and current buyer price for a dependable result.</Text></View>;
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} value={value} onChangeText={onChange} placeholder={placeholder} placeholderTextColor={colors.muted} keyboardType="numeric" /></View>; }
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.line}><Text style={styles.muted}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ controlLabel: { color: colors.primary, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginBottom: 9 }, cropBanner: { backgroundColor: colors.primarySoft, marginBottom: 15 }, cropName: { color: colors.text, fontWeight: '900', fontSize: 17 }, cropHint: { color: colors.muted, lineHeight: 18, fontSize: 11, marginTop: 4 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 }, field: { width: '48%' }, label: { color: colors.primary, fontSize: 9, fontWeight: '900', marginBottom: 6 }, input: { minHeight: 48, backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border, borderRadius: 12, paddingHorizontal: 11, color: colors.text, fontSize: 13 }, result: { backgroundColor: colors.primarySoft, marginTop: 16, marginBottom: 12 }, resultLabel: { color: colors.primary, fontSize: 10, fontWeight: '900', letterSpacing: 1 }, profit: { fontSize: 30, fontWeight: '900', marginVertical: 8 }, line: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 8, marginTop: 8 }, muted: { color: colors.muted, fontSize: 12 }, value: { color: colors.text, fontWeight: '800', fontSize: 12, textAlign: 'right' }, checklist: { marginBottom: 10 }, checkTitle: { color: colors.text, fontWeight: '900' }, checkText: { color: colors.muted, lineHeight: 19, fontSize: 11, marginTop: 5 }, note: { color: colors.muted, lineHeight: 17, fontSize: 10, fontStyle: 'italic' } });
