import { MaterialCommunityIcons } from '@expo/vector-icons';
import * as Location from 'expo-location';
import { useState } from 'react';
import { ActivityIndicator, Alert, Keyboard, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { reverseGeocode, searchPlaces } from './api';
import { Card } from './components';
import { colors } from './theme';
import { FarmLocation } from './types';

export function SettingsScreen({ location, onLocation }: { location: FarmLocation | null; onLocation: (location: FarmLocation) => Promise<void> }) {
  const [query, setQuery] = useState(''); const [results, setResults] = useState<FarmLocation[]>([]); const [busy, setBusy] = useState(false);
  async function gps() { setBusy(true); try { const permission = await Location.requestForegroundPermissionsAsync(); if (!permission.granted) throw new Error('Location permission was not granted.'); const point = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); let farm: FarmLocation = { name: 'My farm', latitude: point.coords.latitude, longitude: point.coords.longitude }; try { farm = await reverseGeocode(farm.latitude, farm.longitude); } catch {} await onLocation(farm); Alert.alert('Farm location saved', farm.name); } catch (e) { Alert.alert('Could not use GPS', e instanceof Error ? e.message : 'Please try again.'); } finally { setBusy(false); } }
  async function search() { if (query.trim().length < 2) return; Keyboard.dismiss(); setBusy(true); try { const found = await searchPlaces(query.trim()); setResults(found); if (!found.length) Alert.alert('No places found', 'Try a nearby town, district, or region.'); } catch { Alert.alert('Search unavailable', 'Check your internet connection and try again.'); } finally { setBusy(false); } }
  async function choose(place: FarmLocation) { await onLocation(place); setResults([]); setQuery(''); Alert.alert('Farm location saved', place.name); }
  return <ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Farm location</Text><Text style={styles.subtitle}>Weather and climate data are calculated for this point.</Text>
    {location ? <Card style={styles.current}><Text style={styles.label}>CURRENT LOCATION</Text><View style={styles.locationRow}><MaterialCommunityIcons name="map-marker" size={24} color={colors.primary} /><View style={styles.flex}><Text style={styles.locationName}>{location.name}</Text><Text style={styles.coords}>{location.latitude.toFixed(4)}, {location.longitude.toFixed(4)}</Text></View></View></Card> : null}
    <Pressable style={styles.gpsButton} onPress={gps} disabled={busy}><MaterialCommunityIcons name="crosshairs-gps" size={23} color="#FFF" /><Text style={styles.gpsText}>Use my current GPS location</Text></Pressable>
    <View style={styles.divider}><View style={styles.line} /><Text style={styles.or}>OR SEARCH</Text><View style={styles.line} /></View>
    <View style={styles.searchRow}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Town, village, or district" placeholderTextColor="#8A948E" style={styles.input} returnKeyType="search" /><Pressable onPress={search} style={styles.searchButton}><MaterialCommunityIcons name="magnify" size={24} color="#FFF" /></Pressable></View>
    {busy ? <ActivityIndicator style={styles.busy} color={colors.primary} /> : null}
    {results.map((place) => <Pressable key={`${place.latitude},${place.longitude}`} onPress={() => choose(place)} style={styles.result}><MaterialCommunityIcons name="map-marker-outline" size={22} color={colors.primary} /><Text numberOfLines={3} style={styles.resultText}>{place.name}</Text><MaterialCommunityIcons name="chevron-right" size={22} color={colors.muted} /></Pressable>)}
    <Card style={styles.privacy}><MaterialCommunityIcons name="shield-check-outline" size={24} color={colors.primary} /><View style={styles.flex}><Text style={styles.privacyTitle}>Stored only on this device</Text><Text style={styles.privacyText}>Your selected coordinates and downloaded forecasts stay in the app's local database. AgroCast has no account or backend server.</Text></View></Card>
    <Text style={styles.credits}>Weather: Open-Meteo · Maps: OpenStreetMap/Nominatim · Climate: NASA POWER · Soil: ISRIC SoilGrids</Text>
  </ScrollView>;
}
const styles = StyleSheet.create({ content: { padding: 20, paddingBottom: 110 }, title: { fontSize: 27, fontWeight: '900', color: colors.text }, subtitle: { color: colors.muted, marginTop: 4, lineHeight: 20 }, current: { marginTop: 18 }, label: { color: colors.primary, fontWeight: '900', fontSize: 11, letterSpacing: 1 }, locationRow: { flexDirection: 'row', gap: 9, marginTop: 10 }, flex: { flex: 1 }, locationName: { color: colors.text, fontWeight: '800', lineHeight: 20 }, coords: { color: colors.muted, marginTop: 4, fontSize: 12 }, gpsButton: { marginTop: 14, height: 54, backgroundColor: colors.primary, borderRadius: 15, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10 }, gpsText: { color: '#FFF', fontWeight: '900' }, divider: { flexDirection: 'row', alignItems: 'center', gap: 10, marginVertical: 22 }, line: { flex: 1, height: 1, backgroundColor: colors.border }, or: { color: colors.muted, fontSize: 11, fontWeight: '800', letterSpacing: 1 }, searchRow: { flexDirection: 'row', gap: 8 }, input: { flex: 1, height: 52, backgroundColor: '#FFF', borderWidth: 1, borderColor: colors.border, borderRadius: 14, paddingHorizontal: 15, color: colors.text, fontSize: 16 }, searchButton: { width: 52, height: 52, backgroundColor: colors.primaryDark, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, busy: { marginTop: 20 }, result: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: colors.border }, resultText: { flex: 1, color: colors.text, lineHeight: 19 }, privacy: { flexDirection: 'row', gap: 12, marginTop: 28, backgroundColor: colors.primarySoft }, privacyTitle: { color: colors.text, fontWeight: '900' }, privacyText: { color: colors.muted, lineHeight: 19, marginTop: 4, fontSize: 13 }, credits: { color: colors.muted, fontSize: 11, lineHeight: 17, textAlign: 'center', marginTop: 22 } });
